import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-300`}
      >
        {children}
        <footer>
          <div className="h-24 bg-slate-400 mt-72 ml-2 mr-2 border-2 text-center border-black">
        <p className="font-bold">About: </p>
        <p className="pl-16 pr-16">This is my assignment project in which I have made 7 distinct pages, modified layout.tsx, made an error page, 1 component that is above mentioned navigation bar and styled them with tailwind-css.</p>
        </div>
        </footer>      
      </body>
    </html>
  );
}
